// 저장소 원본(PRIVACY.md / TERMS.md)의 번역본이다. 원본이 바뀌면 같이 고쳐야 한다.
const supportLink = (
  <a href="mailto:support@1day1ott.com">support@1day1ott.com</a>
);

export function EnglishPrivacyPolicy() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p className="legal-lead">
        The operator of 1DAY 1OTT (the “Operator”) complies with the Personal
        Information Protection Act and other applicable laws of the Republic
        of Korea and processes the personal information of data subjects who
        use the 1DAY 1OTT service (the “Service”) as described below.
      </p>

      <section>
        <h2>1. Purposes and Categories of Personal Information</h2>
        <div className="legal-table-wrap">
          <table>
            <thead>
              <tr>
                <th>Purpose</th>
                <th>Information processed</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Registration and identification of the individual</td>
                <td>Name, email address, and one-way password hash</td>
              </tr>
              <tr>
                <td>Sign-in and security</td>
                <td>
                  Session token, IP address, User-Agent, sign-in time, and
                  session creation and expiration times
                </td>
              </tr>
              <tr>
                <td>Passkey authentication</td>
                <td>
                  Passkey name, public key, credential ID, device type, backup
                  status, transport, AAGUID, and registration time
                </td>
              </tr>
              <tr>
                <td>Providing the Service</td>
                <td>
                  Username, bio, profile image and its file type and size,
                  public-profile setting, federation setting and
                  handle, public key, remote follower Actor and inbox URL,
                  publication status, language, viewing date, content title,
                  content type, external content ID, reaction, note, and
                  viewing platform
                </td>
              </tr>
              <tr>
                <td>Service usage analytics</td>
                <td>
                  Google Analytics client ID, consent status, access time,
                  visited pages and usage events, referrer, device and browser
                  information, and approximate location
                </td>
              </tr>
              <tr>
                <td>Troubleshooting and security</td>
                <td>
                  Request, error and deployment logs, access date and time, and
                  request metadata
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          The Operator does not store plaintext passwords and stores only the
          one-way hash generated by Better Auth. Passkey biometric data never
          leaves the data subject&apos;s device; the Service stores only the
          public key and metadata required for authentication.
        </p>
        <p>
          The browser stores essential session cookies and the language (
          <code>1ott.lang</code>), theme (<code>theme</code>), and analytics
          consent (<code>1ott.analytics-consent</code>) settings. Google
          Analytics loads only after the data subject consents to analytics and
          may use <code>_ga</code> and <code>_ga_*</code> cookies. Advertising
          and personalized marketing features are disabled. The Operator does
          not send names, email addresses, viewing records, or user IDs to
          Google Analytics.
        </p>
      </section>

      <section>
        <h2>2. Legal Basis</h2>
        <p>
          The Operator processes personal information only as necessary to
          enter into and perform the Service agreement, respond to data subject
          requests, secure the Service, and prevent misuse. Optional
          information is processed only when the data subject uses the relevant
          feature.
        </p>
        <p>
          Service usage analytics is based on the data subject&apos;s consent.
          Refusing consent does not limit any core Service feature.
        </p>
        <p>
          The Operator does not provide the Service to children under 14. If the
          Operator learns that personal information belongs to a child under 14,
          it will be deleted without delay.
        </p>
      </section>

      <section>
        <h2>3. Retention and Use Period</h2>
        <ul>
          <li>
            Account information and Service records: until account deletion
            or completion of a deletion request
          </li>
          <li>
            Session information: until the session expires, the data subject
            signs out, or another session is revoked
          </li>
          <li>
            One-time authentication information: until authentication is
            completed or the information expires
          </li>
          <li>
            Troubleshooting and security logs: up to 30 days from creation
          </li>
          <li>
            Google Analytics data: for the period set in the Google Analytics
            property&apos;s data-retention settings and under Google&apos;s
            policies
          </li>
          <li>
            Information subject to a statutory retention duty: for the period
            required by the applicable law
          </li>
        </ul>
        <p>
          The Operator begins deletion without delay after receiving a request.
          Information remaining in backups is used only for recovery and is
          deleted according to the backup cycle.
        </p>
      </section>

      <section>
        <h2>4. Provision to Third Parties and Public Profiles</h2>
        <p>
          The Operator does not sell data subjects&apos; personal information to
          third parties. The Operator does not provide it to third parties
          without the data subject&apos;s consent, except in the following
          cases:
        </p>
        <ul>
          <li>
            Where there is a basis in law, or where an investigative or other
            competent authority makes a request through lawful procedures
          </li>
          <li>
            Where necessary to protect an imminent risk to life, bodily safety,
            or property interests
          </li>
        </ul>
        <p>
          Public profiles are disabled by default. Only when a data subject sets
          a username and personally enables the public option will the username,
          name, bio, profile image, number of entries by viewing date, total
          number of entries, and recent content posters become public. Disabling
          the option makes the profile private again. Profile image files are
          served through a public R2 URL, so a third party that knows or has
          cached the URL may still access it after the public option is disabled.
        </p>
        <p>
          Federation is a separate optional feature and is disabled by default.
          When enabled from My Page, the federation handle, name, bio, profile
          image, Actor data, and public keys become public. Content titles, viewing dates,
          reactions, notes, and public-page URLs may be sent to independent
          ActivityPub servers that follow the account. Those servers may
          process the information across borders and cache or redistribute it
          under their own policies.
        </p>
        <p>
          Disabling federation stops future publication and Actor exposure.
          Deleting an entry sends a deletion activity, but the Operator cannot
          guarantee deletion from independent servers&apos; caches, backups,
          screenshots, or redistributed copies.
        </p>
        <p>
          A public page for a title may show aggregated viewer counts and
          reactions that do not identify a particular individual.
        </p>
      </section>

      <section>
        <h2>5. Entrusted Processing and Cross-Border Transfers</h2>
        <p>The Service uses the infrastructure of the following provider.</p>
        <div className="legal-table-wrap">
          <table>
            <thead>
              <tr>
                <th>Entrusted processor</th>
                <th>Entrusted work</th>
                <th>Information transferred and purpose</th>
                <th>Destination country, timing, and method</th>
                <th>Retention and use period</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Cloudflare, Inc.</td>
                <td>
                  Web hosting, API execution, D1 database, R2 image storage, and security and
                  troubleshooting logs
                </td>
                <td>
                  All Service data listed in Section 1, processed to provide
                  and secure the Service
                </td>
                <td>
                  Transferred over an encrypted network when the Service is
                  used, to the United States and other countries where
                  Cloudflare&apos;s global infrastructure is located
                </td>
                <td>
                  For the period determined by the Service agreement and
                  Cloudflare settings, or until completion of a deletion
                  request
                </td>
              </tr>
              <tr>
                <td>Google LLC</td>
                <td>Service usage analytics through Google Analytics</td>
                <td>
                  Consenting data subject&apos;s client ID, access time, visited
                  pages and usage events, referrer, device and browser
                  information, and approximate location
                </td>
                <td>
                  Transferred over an encrypted network after consent when the
                  Service is used, to the United States and other countries
                  where Google&apos;s global infrastructure is located
                </td>
                <td>
                  For the period set in the Google Analytics property&apos;s
                  data-retention settings and under Google&apos;s policies
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          Cloudflare infrastructure locations may vary with network operations.
          Data subjects who do not want a cross-border transfer may discontinue
          use of the Service and request deletion of their personal
          information. In that event, the Service cannot be provided.
        </p>
        <p>
          To provide content search and details, the server may send search
          terms and content IDs to TMDB and a user-provided YouTube URL and
          video ID to YouTube oEmbed. These requests do not include the
          data subject&apos;s name, email, session token, or viewing history.
        </p>
      </section>

      <section>
        <h2>6. Rights of Data Subjects and How to Exercise Them</h2>
        <p>
          Data subjects may request access to, correction or erasure of,
          suspension of processing of, or withdrawal of consent regarding their
          personal information. Viewing records can be edited, deleted, or
          exported as Markdown directly in the Service, and public profiles and
          federation can be disabled at any time from My Page.
        </p>
        <p>
          Analytics consent can be withdrawn at any time through “Analytics
          settings” in the footer.
        </p>
        <p>
          Send requests to delete an account and all personal information, or
          any other privacy request, to {supportLink}. After verifying the
          requester&apos;s identity, the Operator will provide the result
          within the period required by applicable law. A legal representative
          may exercise a data subject&apos;s rights on their behalf to the
          extent permitted by applicable law.
        </p>
      </section>

      <section>
        <h2>7. Destruction Procedures and Methods</h2>
        <p>
          Personal information is destroyed using a method that makes recovery
          difficult when the retention period ends or the processing purpose is
          fulfilled. Electronic files are logically deleted, and any separate
          printed materials are shredded or incinerated.
        </p>
      </section>

      <section>
        <h2>8. Safety Measures</h2>
        <p>
          The Operator applies the following measures to protect personal
          information:
        </p>
        <ul>
          <li>Encryption in transit over HTTPS</li>
          <li>
            One-way password hashing and Passkey public-key authentication
          </li>
          <li>
            Separation of secrets into environment variables and Cloudflare
            secrets
          </li>
          <li>
            Session-based authentication and per-user data access controls
          </li>
          <li>
            Minimization of access to personal information and security updates
          </li>
        </ul>
      </section>

      <section>
        <h2>9. Privacy Inquiries</h2>
        <ul>
          <li>Contact: Operator of 1DAY 1OTT</li>
          <li>Email: {supportLink}</li>
        </ul>
        <p>
          For consultation or reporting concerning an infringement of personal
          information, data subjects may contact the Personal Information
          Infringement Report Center operated by the Korea Internet &amp;
          Security Agency (KISA) (118 without an area code in Korea), the
          Personal Information Dispute Mediation Committee, the Korean National
          Police Agency, the Supreme Prosecutors&apos; Office, or another
          competent authority.
        </p>
      </section>

      <section>
        <h2>10. Changes to This Policy</h2>
        <p>
          If this Policy changes, the changes and effective date will be
          announced through the Service or repository before they take effect.
          Changes material to user rights will be announced with reasonable
          advance notice.
        </p>
      </section>
    </>
  );
}

export function EnglishTerms() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="legal-lead">
        These Terms set out the conditions for use of the 1DAY 1OTT service (the
        “Service”) provided by the operator of 1DAY 1OTT (the “Operator”), and
        the rights and obligations of the Operator and users.
      </p>

      <section>
        <h2>Article 1. Purpose and Scope</h2>
        <p>
          These Terms apply to the website, related APIs, and other use of the
          Service. By completing registration or continuing to use the Service,
          a user is deemed to have agreed to these Terms and the{" "}
          <a href="/privacy">Privacy Policy</a>.
        </p>
      </section>

      <section>
        <h2>Article 2. Service Features</h2>
        <p>The Service provides the following features free of charge:</p>
        <ul>
          <li>
            Record, view, edit, and delete content a user has watched, together
            with notes
          </li>
          <li>
            Display viewing history as an activity grid, calendar, statistics,
            and similar views
          </li>
          <li>Share a public profile when the user chooses to do so</li>
          <li>
            When separately enabled by the user, accept fediverse follows and
            publish notes to ActivityPub servers
          </li>
          <li>Import and export records in Markdown format</li>
          <li>
            Retrieve content information from external services such as TMDB
            and YouTube
          </li>
        </ul>
        <p>
          The Operator may modify or discontinue features to improve Service
          quality or security, comply with external-service policies, or meet
          operational needs. Material changes will be announced in advance
          where reasonably possible.
        </p>
      </section>

      <section>
        <h2>Article 3. Eligibility and Accounts</h2>
        <p>
          The Service is available only to users aged 14 or older. Users must
          provide accurate, current information and keep their sign-in methods
          secure. A user who notices unusual activity on their account must
          immediately change the password or notify the Operator.
        </p>
        <p>
          Users must not use another person&apos;s information or account
          without authorization, and must not share a single account among
          several people in a way that compromises the security of the Service.
        </p>
      </section>

      <section>
        <h2>Article 4. User Content</h2>
        <p>
          Users retain their rights in content titles, viewing records,
          reactions, notes, and other information they enter (“User Content”).
        </p>
        <p>
          Users grant the Operator a non-exclusive, royalty-free license to
          store, process, display, and back up User Content, and to share it
          within the public scope selected by the user, in each case only as
          necessary to provide the Service. This license is limited to providing
          the Service and ends when the User Content is deleted, except for
          technically necessary backup retention periods and statutory retention
          obligations.
        </p>
        <p>
          Users may enter only information they have the right to post and must
          not infringe another person&apos;s copyright, trademark, privacy, or
          other rights.
        </p>
        <p>
          When a user enables federation, the license above includes permission
          to transmit and display selected User Content to independent
          ActivityPub servers and their users. Disabling federation stops future
          publication. Deleting an entry sends a deletion activity, but removal
          from remote caches, backups, screenshots, or redistributed copies is
          not guaranteed.
        </p>
      </section>

      <section>
        <h2>Article 5. Prohibited Conduct</h2>
        <p>Users must not:</p>
        <ul>
          <li>
            Gain unauthorized access to the Service or another user&apos;s
            account
          </li>
          <li>
            Distribute malware, exploit vulnerabilities, bypass authentication,
            or interfere with security features
          </li>
          <li>
            Place an excessive load on the Service, including through automated
            bulk requests
          </li>
          <li>
            Post illegal or harmful information, another person&apos;s personal
            information, or content that infringes the rights of others
          </li>
          <li>
            Collect or redistribute data in violation of the terms governing
            the Service or external APIs
          </li>
          <li>
            Impersonate the Operator or interfere with operation of the Service
          </li>
        </ul>
        <p>
          The Operator may request that prohibited conduct stop and may limit
          access to content or an account to the extent necessary. Unless the
          matter is urgent, the Operator will inform the user of the reason and
          how to object.
        </p>
      </section>

      <section>
        <h2>Article 6. External Services</h2>
        <p>
          The Service uses third-party services and infrastructure, including
          TMDB, YouTube, Cloudflare, Google Analytics, and, when federation is
          enabled, independent ActivityPub servers. Those providers control the
          accuracy and availability of their information and their own policies.
          An outage of an external service or a change to its policies may
          limit certain features.
        </p>
        <p>
          This service uses TMDB and the TMDB APIs but is not endorsed,
          certified, or otherwise approved by TMDB.
        </p>
      </section>

      <section>
        <h2>Article 7. Privacy</h2>
        <p>
          The <a href="/privacy">Privacy Policy</a> governs the processing of
          personal information. Public profiles and federation are enabled only
          when the user turns on each respective option.
        </p>
      </section>

      <section>
        <h2>Article 8. Discontinuing Use and Deleting an Account</h2>
        <p>
          Users may stop using the Service at any time and may request deletion
          of their account and personal information by contacting {supportLink}.
          Before deletion, users should preserve any records they need using
          the Markdown export feature.
        </p>
        <p>
          If the Operator discontinues the Service, it will give advance notice
          where reasonably possible and provide a reasonable period during which
          users can export their records.
        </p>
      </section>

      <section>
        <h2>Article 9. Warranties and Liability</h2>
        <p>
          The Operator works to provide the Service reliably but does not
          warrant that it will always be uninterrupted or that all information
          will be accurate. The Service is a tool for managing viewing records,
          and information about external content is based on data from each
          provider.
        </p>
        <p>
          Unless caused by the Operator&apos;s willful misconduct or gross
          negligence, the Operator is not liable for damage caused by natural
          disasters, external infrastructure failures, causes attributable to a
          user, or a third party&apos;s unlawful conduct. Nothing in these Terms
          limits consumer rights that cannot be limited or excluded under
          applicable law.
        </p>
      </section>

      <section>
        <h2>Article 10. Changes to These Terms</h2>
        <p>
          The Operator may amend these Terms to the extent permitted by
          applicable law. Changes material to user rights will be announced,
          together with their effective date, through the Service or repository
          before they take effect.
        </p>
      </section>

      <section>
        <h2>Article 11. Governing Law and Disputes</h2>
        <p>
          These Terms are governed by the laws of the Republic of Korea. If a
          dispute arises, the parties will first attempt to resolve it in good
          faith. Any unresolved dispute will be submitted to a court of
          competent jurisdiction under the Civil Procedure Act and other
          applicable laws.
        </p>
      </section>

      <section>
        <h2>Article 12. Contact</h2>
        <ul>
          <li>Operator: Operator of 1DAY 1OTT</li>
          <li>Email: {supportLink}</li>
        </ul>
      </section>
    </>
  );
}
